"""empty message

Revision ID: 09585ba3d682
Revises: 46187199c6f2
Create Date: 2019-08-01 10:32:54.049488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09585ba3d682'
down_revision = '46187199c6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bbs_posts_ibfk_2', 'bbs_posts', type_='foreignkey')
    op.drop_column('bbs_posts', 'puid')
    op.add_column('bbs_replies', sa.Column('rusername', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bbs_replies', 'rusername')
    op.add_column('bbs_posts', sa.Column('puid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('bbs_posts_ibfk_2', 'bbs_posts', 'bbs_user', ['puid'], ['uid'])
    # ### end Alembic commands ###
