"""empty message

Revision ID: 15fd30a9229d
Revises: 542865b956a2
Create Date: 2019-07-29 15:34:31.346397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15fd30a9229d'
down_revision = '542865b956a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bbs_category_ibfk_1', 'bbs_category', type_='foreignkey')
    op.create_foreign_key(None, 'bbs_category', 'bbs_user', ['ccompere'], ['username'], onupdate='CASCADE', ondelete='CASECADE')
    op.drop_column('bbs_user', 'upassword_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bbs_user', sa.Column('upassword_hash', mysql.VARCHAR(length=128), nullable=False))
    op.drop_constraint(None, 'bbs_category', type_='foreignkey')
    op.create_foreign_key('bbs_category_ibfk_1', 'bbs_category', 'bbs_user', ['ccompere'], ['username'])
    # ### end Alembic commands ###
