"""empty message

Revision ID: 542865b956a2
Revises: 
Create Date: 2019-07-28 16:41:08.522029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542865b956a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bbs_category', 'bbs_user', ['ccompere'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bbs_category', type_='foreignkey')
    # ### end Alembic commands ###
