"""empty message

Revision ID: 7582ea4d34df
Revises: 893f6a166352
Create Date: 2019-08-01 10:45:17.802993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7582ea4d34df'
down_revision = '893f6a166352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bbs_posts_ibfk_3', 'bbs_posts', type_='foreignkey')
    op.drop_constraint('bbs_replies_ibfk_1', 'bbs_replies', type_='foreignkey')
    op.drop_column('bbs_replies', 'ruid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bbs_replies', sa.Column('ruid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('bbs_replies_ibfk_1', 'bbs_replies', 'bbs_user', ['ruid'], ['uid'])
    op.create_foreign_key('bbs_posts_ibfk_3', 'bbs_posts', 'bbs_category', ['pcid'], ['cid'])
    # ### end Alembic commands ###
