"""empty message

Revision ID: 9c91614a0180
Revises: 1817f77d89ba
Create Date: 2019-07-30 20:53:51.202860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c91614a0180'
down_revision = '1817f77d89ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bbs_replies', sa.Column('rpid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bbs_replies', 'bbs_posts', ['rpid'], ['pid'])
    op.alter_column('bbs_user', 'upassword',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bbs_user', 'upassword',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.drop_constraint(None, 'bbs_replies', type_='foreignkey')
    op.drop_column('bbs_replies', 'rpid')
    # ### end Alembic commands ###
