"""empty message

Revision ID: c7fb689a905b
Revises: 9c91614a0180
Create Date: 2019-07-31 16:20:37.298766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7fb689a905b'
down_revision = '9c91614a0180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('plastreplyid', table_name='bbs_posts')
    op.create_foreign_key(None, 'bbs_replies', 'bbs_posts', ['rpid'], ['pid'])
    op.add_column('bbs_user', sa.Column('ulevel', sa.String(length=128), nullable=True))
    op.add_column('bbs_user', sa.Column('uphoto', sa.String(length=200), nullable=True))
    op.add_column('bbs_user', sa.Column('ustatus', sa.String(length=60), nullable=True))
    op.alter_column('bbs_user', 'upassword',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.drop_column('bbs_user', 'uportrait')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bbs_user', sa.Column('uportrait', mysql.VARCHAR(length=200), nullable=True))
    op.alter_column('bbs_user', 'upassword',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.drop_column('bbs_user', 'ustatus')
    op.drop_column('bbs_user', 'uphoto')
    op.drop_column('bbs_user', 'ulevel')
    op.drop_constraint(None, 'bbs_replies', type_='foreignkey')
    op.create_index('plastreplyid', 'bbs_posts', ['plastreplyuser'], unique=False)
    # ### end Alembic commands ###
